# Generated by Django 5.0 on 2024-08-08 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0006_company_facebook_url_company_instagram_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("seo_title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "seo_keywords",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=150, verbose_name="Code"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=150, verbose_name="Title"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=128, null=True, unique=True, verbose_name="Slug"
                    ),
                ),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tag_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
