# Generated by Django 5.1.1 on 2024-11-22 14:26

import apps.tag.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_alter_company_image"),
        ("tag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillTag",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(blank=True, max_length=150, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=128, null=True, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "color",
                    apps.tag.utils.HEXColorField(
                        help_text="Use a valid HEX color code, e.g., #FFFFFF or #FFF",
                        max_length=7,
                        verbose_name="HEX Color",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skill_tag_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SkillTag",
                "verbose_name_plural": "Skill Tags",
            },
        ),
    ]
