# Generated by Django 4.1.3 on 2023-10-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_companym2mcontact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="seo_description",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="seo_keywords",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="seo_title",
        ),
    ]
