# Generated by Django 4.1.3 on 2023-05-15 11:29

from django.db import migrations
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_code_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="content",
            field=tinymce_4.fields.TinyMCEModelField(
                blank=True, null=True, verbose_name="Content"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="content",
            field=tinymce_4.fields.TinyMCEModelField(
                blank=True, null=True, verbose_name="Content"
            ),
        ),
    ]
