# Generated by Django 4.1.3 on 2023-05-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_category_content_product_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=128, null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
