# Generated by Django 4.1.3 on 2023-06-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_certificate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
            },
        ),
    ]
