# Generated by Django 4.1.3 on 2023-06-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_certificate_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                max_length=128, null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
