# Generated by Django 4.1.3 on 2023-07-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="code",
            field=models.CharField(blank=True, max_length=150, verbose_name="Code"),
        ),
    ]
