# Generated by Django 4.1.3 on 2023-12-17 22:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce_4.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_certificate_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotationRequest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client",
                    models.CharField(blank=True, max_length=150, verbose_name="Client"),
                ),
                ("contact_date", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    tinymce_4.fields.TinyMCEModelField(
                        blank=True, null=True, verbose_name="Content"
                    ),
                ),
            ],
            options={
                "verbose_name": "QuotationRequest",
                "verbose_name_plural": "QuotationRequests",
            },
        ),
        migrations.CreateModel(
            name="QuotationRequestDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "price_total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "quotation_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotation_request_detail",
                        to="product.quotationrequest",
                    ),
                ),
            ],
        ),
    ]
