# Generated by Django 4.1.3 on 2023-12-17 23:15

from django.db import migrations, models
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_quotationrequest_quotationrequestdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationrequest",
            name="client",
            field=models.CharField(blank=True, max_length=150, verbose_name="client"),
        ),
        migrations.AlterField(
            model_name="quotationrequest",
            name="description",
            field=tinymce_4.fields.TinyMCEModelField(
                blank=True, null=True, verbose_name="description"
            ),
        ),
    ]
