# Generated by Django 4.1.3 on 2024-01-24 15:23

from django.db import migrations
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_alter_quotationrequest_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=tinymce_4.fields.TinyMCEModelField(
                blank=True, null=True, verbose_name="description"
            ),
        ),
    ]
