# Generated by Django 4.1.3 on 2024-01-26 21:40

from django.db import migrations
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_alter_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=tinymce_4.fields.TinyMCEModelField(blank=True, null=True),
        ),
    ]
