# Generated by Django 5.0 on 2024-08-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_company_facebook_url_company_instagram_url_and_more"),
        ("product", "0014_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_company",
                to="company.company",
            ),
        ),
    ]
