# Generated by Django 5.0 on 2024-08-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_category_company"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(
                blank=True,
                related_name="product_tags",
                to="tag.tag",
                verbose_name="Tags",
            ),
        ),
    ]
