# Generated by Django 5.0 on 2024-08-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_product_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="certificado",
        ),
    ]
