# Generated by Django 5.1.1 on 2024-10-16 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0019_alter_productimage_options_productimage_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flavor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Flavor Name")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flavors",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flavor",
                "verbose_name_plural": "Flavors",
            },
        ),
        migrations.CreateModel(
            name="Packaging",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(max_length=50, verbose_name="Size or Packaging"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Packaging Price"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packagings",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Packaging",
                "verbose_name_plural": "Packagings",
            },
        ),
        migrations.DeleteModel(
            name="Certificate",
        ),
    ]
