# Generated by Django 5.1.1 on 2024-10-18 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0020_flavor_packaging_product_flavors_product_packagings_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Characteristic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Feature Name",
                    ),
                ),
                (
                    "feature_value",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Feature Value",
                    ),
                ),
                (
                    "is_key_feature",
                    models.BooleanField(default=False, verbose_name="Is Key Feature"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characteristics",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
