# Generated by Django 5.1.1 on 2024-10-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0021_characteristic"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="is_info_image",
            field=models.BooleanField(default=False, verbose_name="Is Info Image"),
        ),
    ]
