# Generated by Django 5.1.1 on 2024-10-20 10:56

import apps.product.schema.enums.enums
import graphene.types.enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0023_remove_product_content_product_is_best_seller_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="objective",
            field=models.CharField(
                choices=apps.product.schema.enums.enums.ObjectiveChoices.choices,
                default=graphene.types.enum.ObjectiveChoices["FITNESS"],
                max_length=200,
                verbose_name="Objetivo",
            ),
        ),
    ]
