# Generated by Django 5.1.1 on 2024-11-10 22:24

import apps.product.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0024_product_objective"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.product.utils.custom_product_upload_to,
                verbose_name="Product File",
            ),
        ),
    ]
