# Generated by Django 5.1.1 on 2024-11-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0025_alter_productimage_image"),
        ("tag", "0002_skilltag"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="skill_tags",
            field=models.ManyToManyField(
                blank=True, related_name="skill_tag_products", to="tag.skilltag"
            ),
        ),
    ]
