# Generated by Django 5.1.1 on 2025-01-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0028_faq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="suggestion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
