# Generated by Django 4.1.3 on 2023-08-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0003_banner_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customwebpage",
            name="comercial_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Comercial Name"
            ),
        ),
        migrations.AddField(
            model_name="customwebpage",
            name="ruc",
            field=models.CharField(blank=True, max_length=150, verbose_name="RUC"),
        ),
    ]
