# Generated by Django 5.1.1 on 2024-10-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0004_customwebpage_comercial_name_customwebpage_ruc"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="image_responsive",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="banner-responsive",
                verbose_name="image_responsive",
            ),
        ),
    ]
