# Generated by Django 5.1.1 on 2024-10-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0005_banner_image_responsive"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="first_slider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="banner",
            name="second_slider",
            field=models.BooleanField(default=False),
        ),
    ]
