# Generated by Django 5.1.1 on 2024-10-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0006_banner_first_slider_banner_second_slider"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="url_redirect",
            field=models.URLField(
                blank=True, default="https://demo.demolitorprotein.com/"
            ),
        ),
    ]
