# Generated by Django 4.1.3 on 2023-04-17 07:22

import apps.company.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ubigeos", "0002_auto_20210325_1040"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("seo_title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "seo_keywords",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "social_reason",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Razon Social"
                    ),
                ),
                (
                    "comercial_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Comercial Name"
                    ),
                ),
                (
                    "type_company",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNIPERSONAL", "EMPRESA UNIPERSONAL"),
                            ("EIRL", "E.I.R.L"),
                            ("SRL", "S.R.L"),
                            ("SA", "SOCIEDAD ANONIMA S.A."),
                            ("SAA", "SOCIEDAD ANONIMA ABIERTA S.A.A."),
                            ("SAC", "SOCIEDAD ANONIMA CERRADA S.A.C."),
                        ],
                        max_length=60,
                        null=True,
                        verbose_name="Genero",
                    ),
                ),
                (
                    "comercial_activity",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Comercial Activity"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.company.utils.custom_company_upload_to,
                        verbose_name="image_category",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Address"
                    ),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=150, verbose_name="Email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Address"
                    ),
                ),
                (
                    "distrito",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ubigeos.distrito",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ubigeos.provincia",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ubigeos.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
