# Generated by Django 4.1.3 on 2023-05-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="phone_number"
            ),
        ),
    ]
