# Generated by Django 4.1.3 on 2023-10-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_companym2mcontact"),
        ("company", "0002_alter_company_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="contacts",
            field=models.ManyToManyField(
                related_name="company_contacts", to="contact.companym2mcontact"
            ),
        ),
    ]
