# Generated by Django 4.1.3 on 2023-10-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_remove_contact_seo_description_and_more"),
        ("company", "0003_company_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="company_contacts",
                to="contact.companym2mcontact",
            ),
        ),
    ]
