# Generated by Django 5.1.1 on 2024-11-12 18:01

import apps.company.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_company_facebook_url_company_instagram_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.company.utils.custom_company_upload_to,
                verbose_name="image_logo_company",
            ),
        ),
    ]
